// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: corpus.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "corpus.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* Example_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Example_reflection_ = NULL;
const ::google::protobuf::Descriptor* Example_Trigger_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Example_Trigger_reflection_ = NULL;
const ::google::protobuf::Descriptor* Corpus_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Corpus_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_corpus_2eproto() {
  protobuf_AddDesc_corpus_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "corpus.proto");
  GOOGLE_CHECK(file != NULL);
  Example_descriptor_ = file->message_type(0);
  static const int Example_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Example, words_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Example, trigger_),
  };
  Example_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Example_descriptor_,
      Example::default_instance_,
      Example_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Example, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Example, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Example));
  Example_Trigger_descriptor_ = Example_descriptor_->nested_type(0);
  static const int Example_Trigger_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Example_Trigger, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Example_Trigger, trigger_),
  };
  Example_Trigger_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Example_Trigger_descriptor_,
      Example_Trigger::default_instance_,
      Example_Trigger_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Example_Trigger, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Example_Trigger, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Example_Trigger));
  Corpus_descriptor_ = file->message_type(1);
  static const int Corpus_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Corpus, example_),
  };
  Corpus_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Corpus_descriptor_,
      Corpus::default_instance_,
      Corpus_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Corpus, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Corpus, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Corpus));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_corpus_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Example_descriptor_, &Example::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Example_Trigger_descriptor_, &Example_Trigger::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Corpus_descriptor_, &Corpus::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_corpus_2eproto() {
  delete Example::default_instance_;
  delete Example_reflection_;
  delete Example_Trigger::default_instance_;
  delete Example_Trigger_reflection_;
  delete Corpus::default_instance_;
  delete Corpus_reflection_;
}

void protobuf_AddDesc_corpus_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\014corpus.proto\"c\n\007Example\022\r\n\005words\030\001 \003(\t"
    "\022!\n\007trigger\030\002 \003(\0132\020.Example.Trigger\032&\n\007T"
    "rigger\022\n\n\002id\030\001 \002(\005\022\017\n\007trigger\030\002 \002(\t\"#\n\006C"
    "orpus\022\031\n\007example\030\001 \003(\0132\010.Example", 152);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "corpus.proto", &protobuf_RegisterTypes);
  Example::default_instance_ = new Example();
  Example_Trigger::default_instance_ = new Example_Trigger();
  Corpus::default_instance_ = new Corpus();
  Example::default_instance_->InitAsDefaultInstance();
  Example_Trigger::default_instance_->InitAsDefaultInstance();
  Corpus::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_corpus_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_corpus_2eproto {
  StaticDescriptorInitializer_corpus_2eproto() {
    protobuf_AddDesc_corpus_2eproto();
  }
} static_descriptor_initializer_corpus_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int Example_Trigger::kIdFieldNumber;
const int Example_Trigger::kTriggerFieldNumber;
#endif  // !_MSC_VER

Example_Trigger::Example_Trigger()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Example.Trigger)
}

void Example_Trigger::InitAsDefaultInstance() {
}

Example_Trigger::Example_Trigger(const Example_Trigger& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Example.Trigger)
}

void Example_Trigger::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  id_ = 0;
  trigger_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Example_Trigger::~Example_Trigger() {
  // @@protoc_insertion_point(destructor:Example.Trigger)
  SharedDtor();
}

void Example_Trigger::SharedDtor() {
  if (trigger_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete trigger_;
  }
  if (this != default_instance_) {
  }
}

void Example_Trigger::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Example_Trigger::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Example_Trigger_descriptor_;
}

const Example_Trigger& Example_Trigger::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_corpus_2eproto();
  return *default_instance_;
}

Example_Trigger* Example_Trigger::default_instance_ = NULL;

Example_Trigger* Example_Trigger::New() const {
  return new Example_Trigger;
}

void Example_Trigger::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    id_ = 0;
    if (has_trigger()) {
      if (trigger_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        trigger_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Example_Trigger::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Example.Trigger)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 id = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_trigger;
        break;
      }

      // required string trigger = 2;
      case 2: {
        if (tag == 18) {
         parse_trigger:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_trigger()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->trigger().data(), this->trigger().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "trigger");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Example.Trigger)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Example.Trigger)
  return false;
#undef DO_
}

void Example_Trigger::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Example.Trigger)
  // required int32 id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->id(), output);
  }

  // required string trigger = 2;
  if (has_trigger()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->trigger().data(), this->trigger().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "trigger");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->trigger(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:Example.Trigger)
}

::google::protobuf::uint8* Example_Trigger::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Example.Trigger)
  // required int32 id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->id(), target);
  }

  // required string trigger = 2;
  if (has_trigger()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->trigger().data(), this->trigger().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "trigger");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->trigger(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Example.Trigger)
  return target;
}

int Example_Trigger::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->id());
    }

    // required string trigger = 2;
    if (has_trigger()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->trigger());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Example_Trigger::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Example_Trigger* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Example_Trigger*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Example_Trigger::MergeFrom(const Example_Trigger& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_trigger()) {
      set_trigger(from.trigger());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Example_Trigger::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Example_Trigger::CopyFrom(const Example_Trigger& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Example_Trigger::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void Example_Trigger::Swap(Example_Trigger* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(trigger_, other->trigger_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Example_Trigger::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Example_Trigger_descriptor_;
  metadata.reflection = Example_Trigger_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int Example::kWordsFieldNumber;
const int Example::kTriggerFieldNumber;
#endif  // !_MSC_VER

Example::Example()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Example)
}

void Example::InitAsDefaultInstance() {
}

Example::Example(const Example& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Example)
}

void Example::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Example::~Example() {
  // @@protoc_insertion_point(destructor:Example)
  SharedDtor();
}

void Example::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Example::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Example::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Example_descriptor_;
}

const Example& Example::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_corpus_2eproto();
  return *default_instance_;
}

Example* Example::default_instance_ = NULL;

Example* Example::New() const {
  return new Example;
}

void Example::Clear() {
  words_.Clear();
  trigger_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Example::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Example)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated string words = 1;
      case 1: {
        if (tag == 10) {
         parse_words:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_words()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->words(this->words_size() - 1).data(),
            this->words(this->words_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "words");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_words;
        if (input->ExpectTag(18)) goto parse_trigger;
        break;
      }

      // repeated .Example.Trigger trigger = 2;
      case 2: {
        if (tag == 18) {
         parse_trigger:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_trigger()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_trigger;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Example)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Example)
  return false;
#undef DO_
}

void Example::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Example)
  // repeated string words = 1;
  for (int i = 0; i < this->words_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
    this->words(i).data(), this->words(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE,
    "words");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->words(i), output);
  }

  // repeated .Example.Trigger trigger = 2;
  for (int i = 0; i < this->trigger_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->trigger(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:Example)
}

::google::protobuf::uint8* Example::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Example)
  // repeated string words = 1;
  for (int i = 0; i < this->words_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->words(i).data(), this->words(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "words");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(1, this->words(i), target);
  }

  // repeated .Example.Trigger trigger = 2;
  for (int i = 0; i < this->trigger_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->trigger(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Example)
  return target;
}

int Example::ByteSize() const {
  int total_size = 0;

  // repeated string words = 1;
  total_size += 1 * this->words_size();
  for (int i = 0; i < this->words_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->words(i));
  }

  // repeated .Example.Trigger trigger = 2;
  total_size += 1 * this->trigger_size();
  for (int i = 0; i < this->trigger_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->trigger(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Example::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Example* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Example*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Example::MergeFrom(const Example& from) {
  GOOGLE_CHECK_NE(&from, this);
  words_.MergeFrom(from.words_);
  trigger_.MergeFrom(from.trigger_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Example::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Example::CopyFrom(const Example& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Example::IsInitialized() const {

  if (!::google::protobuf::internal::AllAreInitialized(this->trigger())) return false;
  return true;
}

void Example::Swap(Example* other) {
  if (other != this) {
    words_.Swap(&other->words_);
    trigger_.Swap(&other->trigger_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Example::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Example_descriptor_;
  metadata.reflection = Example_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int Corpus::kExampleFieldNumber;
#endif  // !_MSC_VER

Corpus::Corpus()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Corpus)
}

void Corpus::InitAsDefaultInstance() {
}

Corpus::Corpus(const Corpus& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Corpus)
}

void Corpus::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Corpus::~Corpus() {
  // @@protoc_insertion_point(destructor:Corpus)
  SharedDtor();
}

void Corpus::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Corpus::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Corpus::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Corpus_descriptor_;
}

const Corpus& Corpus::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_corpus_2eproto();
  return *default_instance_;
}

Corpus* Corpus::default_instance_ = NULL;

Corpus* Corpus::New() const {
  return new Corpus;
}

void Corpus::Clear() {
  example_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Corpus::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Corpus)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .Example example = 1;
      case 1: {
        if (tag == 10) {
         parse_example:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_example()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_example;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Corpus)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Corpus)
  return false;
#undef DO_
}

void Corpus::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Corpus)
  // repeated .Example example = 1;
  for (int i = 0; i < this->example_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->example(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:Corpus)
}

::google::protobuf::uint8* Corpus::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Corpus)
  // repeated .Example example = 1;
  for (int i = 0; i < this->example_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->example(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Corpus)
  return target;
}

int Corpus::ByteSize() const {
  int total_size = 0;

  // repeated .Example example = 1;
  total_size += 1 * this->example_size();
  for (int i = 0; i < this->example_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->example(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Corpus::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Corpus* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Corpus*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Corpus::MergeFrom(const Corpus& from) {
  GOOGLE_CHECK_NE(&from, this);
  example_.MergeFrom(from.example_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Corpus::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Corpus::CopyFrom(const Corpus& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Corpus::IsInitialized() const {

  if (!::google::protobuf::internal::AllAreInitialized(this->example())) return false;
  return true;
}

void Corpus::Swap(Corpus* other) {
  if (other != this) {
    example_.Swap(&other->example_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Corpus::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Corpus_descriptor_;
  metadata.reflection = Corpus_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
